// ─── Translatable copy for the Awesomic homepage (EN + RO) ────────────────
// Source design: claude.ai/design/p/019e130a-b156-7a53-9abe-2feed797f07c

export type AccentPart = { t: string; c?: string; w?: number };

export const ACCENT = {
  cyan: "#64CEFB",
  purple: "#a78bfa",
  green: "#4ade80",
} as const;

export type AccentHeading = [AccentPart[], AccentPart[]];

export type HomeCopy = {
  meta: { title: string; description: string };
  banner: { text: string; cta: string };
  navLinks: [string, string][];
  signIn: string;
  dashboardLabel: string;
  getStarted: string;
  hero: {
    headline1: string;
    headlineLead: string;
    cycleWords: string[];
    lead: string;
    emailPlaceholder: string;
    submitLabel: string;
    liveIn: string;
    oneTimeFrom: string;
    previewLabel: string;
    deployReady: string;
  };
  problem: {
    eyebrow: string;
    heading: [AccentPart[], AccentPart[]];
    lead: AccentPart[];
    rows: { lead: AccentPart[]; key: AccentPart[] }[];
  };
  how: {
    eyebrow: string;
    heading: AccentHeading;
    lead: AccentPart[];
    steps: [string, string][];
    liveStepTitle: AccentPart[];
    liveBadge: string;
  };
  examples: {
    eyebrow: string;
    heading: AccentHeading;
    viewAll: string;
    previewTag: string;
    decorativeTag: string;
    decorText: [string, string];
    tiles: { name: string; badges?: string[] }[];
  };
  stats: [string, string][];
  ownership: {
    eyebrow: string;
    heading: AccentHeading;
    lead: AccentPart[];
    badges: string[];
    repoLabel: string;
    repoFiles: string;
    deployLabel: string;
    deployUrl: string;
    readyBadge: string;
  };
  math: {
    eyebrow: string;
    heading: string;
    lead: string;
    traditional: { colHead: string; price: string; priceSub: string; rows: string[] };
    insixlive: { badge: string; pill: string; price: string; priceSub: string; rows: string[] };
  };
  pricing: {
    eyebrow: string;
    heading: AccentHeading;
    lead: AccentPart[];
    popularBadge: string;
    plans: { name: string; price: string; tag: string; items: string[]; muted?: string; cta: string; after: string; featured?: boolean }[];
    note: { badge: string; text: string };
  };
  domains: {
    eyebrow: string;
    heading: AccentHeading;
    lead: AccentPart[];
    exampleDomain: string;
    registrars: string[];
    bar1: { domain: string; status: string };
    bar2: { domain: string; status: string };
  };
  proof: {
    eyebrow: string;
    heading: AccentHeading;
    lead: string;
    testimonials: { initials: string; name: string; biz: string; quote: string }[];
  };
  faq: { eyebrow: string; heading: AccentPart[]; lead: AccentPart[]; items: [string, string][] };
  final: { eyebrow: string; heading: AccentPart[]; lead: AccentPart[]; secondaryCta: string };
  footer: {
    blurb: string;
    groups: { title: string; links: { href: string; label: string }[] }[];
    accountTitle: string;
    createSite: string;
    supportTitle: string;
    supportEmail: string;
    copyright: string;
    builtWith: string;
  };
};

export const EN: HomeCopy = {
  meta: { title: "insixlive — Own your website. Don't rent it.", description: "A complete, professional website generated by AI and deployed to your own Vercel account. Pay once. Own the code. No monthly rent." },
  banner: { text: "insixlive is in private beta — building real websites for small businesses across the EU.", cta: "Join the waitlist" },
  navLinks: [["#how", "How it works"], ["#examples", "Examples"], ["#pricing", "Pricing"], ["#faq", "FAQ"]],
  signIn: "Sign in",
  dashboardLabel: "Dashboard",
  getStarted: "Get started",
  hero: {
    headline1: "Professional websites.",
    headlineLead: "Deployed to ",
    cycleWords: ["your account.", "your domain.", "your code.", "your business."],
    lead: "Describe your business. AI generates the site. Deployed to your own Vercel account — six minutes, one-time payment, yours forever.",
    emailPlaceholder: "you@yourbusiness.com",
    submitLabel: "Get started",
    liveIn: "● Live in ~6 minutes",
    oneTimeFrom: "● €59.99 one-time",
    previewLabel: "product preview — live website",
    deployReady: "deploy · ready",
  },
  problem: {
    eyebrow: "The trap",
    heading: [
      [{ t: "Builders lock you in." }],
      [{ t: "Agencies charge " }, { t: "thousands.", c: "#a78bfa", w: 600 }],
    ],
    lead: [
      { t: "Your Instagram account stays online around the clock — and you " },
      { t: "don't pay", c: "#4ade80", w: 600 },
      { t: " a monthly fee just to keep it there. Your site can work the same way. Some people charge you every month to keep your site live — that's a " },
      { t: "scheme", c: "#a78bfa", w: 600 },
      { t: ". A professional website shouldn't mean a monthly subscription or an agency retainer. Your business deserves " },
      { t: "real code you own", c: "#4ade80", w: 600 },
      { t: " — not rent." },
    ],
    rows: [
      {
        lead: [{ t: "Like Instagram" }],
        key: [{ t: "Always online — no monthly fee just to exist." }],
      },
      {
        lead: [{ t: "Your site" }],
        key: [{ t: "Pay once, stay live — same idea." }],
      },
      {
        lead: [{ t: "What others do" }],
        key: [
          { t: "Charge you every month — " },
          { t: "rent on your own code", c: "#a78bfa", w: 600 },
          { t: "." },
        ],
      },
      {
        lead: [{ t: "What you get here" }],
        key: [
          { t: "Real code you own. " },
          { t: "No lock-in", c: "#4ade80", w: 600 },
          { t: ", no retainer." },
        ],
      },
    ],
  },
  how: {
    eyebrow: "From prompt to live",
    heading: [
      [{ t: "Six steps." }],
      [{ t: "One live " }, { t: "website.", c: ACCENT.green, w: 600 }],
    ],
    lead: [
      { t: "Builders take days. Agencies take weeks. We take " },
      { t: "six minutes", c: ACCENT.cyan, w: 600 },
      { t: "." },
    ],
    steps: [
      ["Describe your business", "Name, services, location, audience, and tone."],
      ["Choose the style", "Colors, typography, layout — your aesthetic."],
      ["Select your pages", "Home, About, Services, Contact, Booking."],
      ["Confirm the brief", "Review the plan before generation begins."],
      ["Pay once", "Stripe checkout. No recurring charge."],
      ["Go live", "Generated and deployed to your Vercel — in ~6 minutes."],
    ],
    liveStepTitle: [{ t: "Go " }, { t: "live", c: ACCENT.green, w: 600 }],
    liveBadge: "Live",
  },
  examples: {
    eyebrow: "Selected work",
    heading: [
      [{ t: "Websites built" }],
      [{ t: "with " }, { t: "insixlive.", c: ACCENT.cyan, w: 600 }],
    ],
    viewAll: "View all templates",
    previewTag: "live site",
    decorativeTag: "decorative",
    decorText: ["Design that", "converts visitors."],
    tiles: [
      { name: "Acme Plumbing", badges: ["Trades & Services"] },
      { name: "Maria's Hair", badges: ["Beauty & Lifestyle"] },
      { name: "", badges: [] },
      { name: "Bistro Marin", badges: ["Food & Hospitality"] },
      { name: "Lia · Photo", badges: ["Portfolio & Creative"] },
      { name: "Forge Fitness", badges: ["Health & Fitness"] },
    ],
  },
  stats: [
    ["~6 min", "From brief to a live, deployed website"],
    ["100%", "Code ownership — every file is yours"],
    ["€0", "Monthly fees after launch. Pay once, then free."],
    ["€10", "Flat-rate edits — no surprise invoices"],
  ],
  ownership: {
    eyebrow: "Ownership",
    heading: [
      [{ t: "You don't rent your website." }],
      [{ t: "You own " }, { t: "every line.", c: ACCENT.green, w: 600 }],
    ],
    lead: [
      { t: "Most builders keep your business on " },
      { t: "their platform", c: ACCENT.purple, w: 600 },
      { t: ". insixlive deploys real Next.js to " },
      { t: "your Vercel account", c: ACCENT.cyan, w: 600 },
      { t: " — yours to keep, modify, or move." },
    ],
    badges: ["Your Vercel account", "Standard Next.js", "Yours forever"],
    repoLabel: "repo · acme-plumbing",
    repoFiles: "app/page.tsx · components/ · public/",
    deployLabel: "deployment",
    deployUrl: "acme-plumbing.vercel.app",
    readyBadge: "● Ready",
  },
  math: {
    eyebrow: "The numbers",
    heading: "The numbers speak.",
    lead: "Agency quotes vs. insixlive — same outcome, fraction of the cost. One payment, your code, your Vercel.",
    traditional: {
      colHead: "Traditional website",
      price: "€1,000+",
      priceSub: "upfront, then monthly fees",
      rows: ["Weeks of back-and-forth", "Locked inside a closed platform", "Every small change = an invoice", "You never fully own the result"],
    },
    insixlive: {
      badge: "insixlive",
      pill: "One-time",
      price: "€59.99",
      priceSub: "one-time · hosting free on Vercel",
      rows: ["Live in ~6 minutes", "Deployed to your own Vercel", "Full source code in your inbox", "No subscription, ever"],
    },
  },
  pricing: {
    eyebrow: "Pricing",
    heading: [
      [{ t: "One-time pricing.", c: ACCENT.green, w: 600 }],
      [{ t: "No monthly " }, { t: "website rent.", c: ACCENT.purple, w: 600 }],
    ],
    lead: [
      { t: "Same result as an agency, a fraction of the cost. " },
      { t: "One payment", c: ACCENT.green, w: 600 },
      { t: ", your code, your Vercel." },
    ],
    popularBadge: "Most popular",
    plans: [
      { name: "Website", price: "€59.99", tag: "Your complete site. No edits included.", items: ["AI-generated professional website", "Deployed to your Vercel account", "Full source code ownership", "Mobile-responsive · SSL · domain ready"], muted: "0 free edits", cta: "Get started", after: "€10.00 per edit after launch", featured: true },
      { name: "Pro", price: "€69.99", tag: "I want to refine my site.", items: ["Everything in Website", "5 free edits included", "Edit tracking in your dashboard", "Priority email support", "Best if you expect changes"], cta: "Get Pro", after: "€10.00 per edit after the first 5" },
      { name: "Premium", price: "€89.99", tag: "I want room to adjust.", items: ["Everything in Pro", "15 free edits included", "Priority generation queue", "1:1 onboarding call (optional)", "Best for evolving businesses"], cta: "Get Premium", after: "€10.00 per edit after the first 15" },
    ],
    note: { badge: "Note", text: "Need a single change later? Request edits from your dashboard for €10.00 per change. Custom domains are not included and usually cost €12–30/year." },
  },
  domains: {
    eyebrow: "Domains",
    heading: [
      [{ t: "Use your " }, { t: "own domain.", c: ACCENT.cyan, w: 600 }],
      [{ t: "Or buy one separately." }],
    ],
    lead: [
      { t: "Your site goes " },
      { t: "live first", c: ACCENT.green, w: 600 },
      { t: " on a Vercel URL. Then connect a custom domain like " },
      { t: "yourbusiness.com", c: ACCENT.cyan, w: 600 },
      { t: " — one you own or buy from any registrar." },
    ],
    exampleDomain: "yourbusiness.com",
    registrars: ["GoDaddy", "Namecheap", "Porkbun", "Cloudflare"],
    bar1: { domain: "acme-plumbing.vercel.app", status: "● Live" },
    bar2: { domain: "acmeplumbing.com", status: "● Connected" },
  },
  proof: {
    eyebrow: "Clients",
    heading: [
      [{ t: "Built for small business owners" }],
      [{ t: "without " }, { t: "agency prices.", c: ACCENT.purple, w: 600 }],
    ],
    lead: "Tested with salons, trades, clinics, and freelancers across the EU during private beta.",
    testimonials: [
      { initials: "ML", name: "Markus Lehmann", biz: "Acme Plumbing · Munich · Pro", quote: "I described the business in two sentences. Six minutes later I had a website I could send to the printer. No subscription, no monthly bill." },
      { initials: "MC", name: "Maria Coelho", biz: "Maria's Hair · Lisbon · Basic", quote: "My old site was on a builder I paid €18/month for. I rebuilt with insixlive and now I just own the code. The math is brutal in their favor." },
      { initials: "AK", name: "Dr. Anna Kohl", biz: "Kohl Dental · Berlin · Premium", quote: "I wanted a clean, calm, trustworthy site. The first draft was 80% there — three small edits and we shipped it." },
    ],
  },
  faq: {
    eyebrow: "FAQ",
    heading: [{ t: "Questions " }, { t: "answered.", c: ACCENT.cyan, w: 600 }],
    lead: [{ t: "Everything you need to know " }, { t: "before you start.", c: ACCENT.green, w: 600 }],
    items: [
      ["Do I need to know how to code?", "No. You describe your business in plain English. We generate the site, deploy it, and you can edit later through your dashboard or directly in the code."],
      ["Who owns the website?", "You do. The code is yours, the Vercel project is in your account, and the domain (if you connect one) belongs to you."],
      ["Is there a subscription?", "No subscription on the generated website. You pay once. Vercel hosting is free for most small sites. Custom domains are paid separately to a registrar."],
      ["What happens after I pay?", "We generate the site, push it to your Vercel, and send you the deploy URL. The whole flow takes around six minutes."],
      ["Can I connect my own domain?", "Yes. Connect a domain from any registrar (GoDaddy, Namecheap, Porkbun, Cloudflare, etc.) or buy a new one separately."],
      ["Can I move away from Vercel?", "Yes. The code is a standard Next.js project — host it anywhere that runs Node or static sites."],
    ],
  },
  final: {
    eyebrow: "Get started",
    heading: [
      { t: "Six minutes from now, your website is " },
      { t: "live.", c: ACCENT.green, w: 600 },
    ],
    lead: [
      { t: "Brief to deployed — AI generates your code and ships it to " },
      { t: "your account.", c: ACCENT.cyan, w: 600 },
    ],
    secondaryCta: "See pricing",
  },
  footer: {
    blurb: "Real websites, generated by AI, deployed to your account. Own it — don't rent it.",
    groups: [
      {
        title: "Product",
        links: [
          { href: "#how", label: "How it works" },
          { href: "#examples", label: "Examples" },
          { href: "#pricing", label: "Pricing" },
          { href: "#faq", label: "FAQ" },
        ],
      },
      {
        title: "Legal",
        links: [
          { href: "/privacy?lang=en", label: "Privacy" },
          { href: "/terms?lang=en", label: "Terms" },
          { href: "/email-preferences", label: "Email preferences" },
        ],
      },
    ],
    accountTitle: "Account",
    createSite: "Create your site",
    supportTitle: "Support",
    supportEmail: "support@insixlive.com",
    copyright: "© 2026 insixlive. Own your website. Don't rent it.",
    builtWith: "Built with Next.js · Deployed on Vercel",
  },
};

export const RO: HomeCopy = {
  meta: { title: "insixlive — Deține-ți site-ul. Nu-l închiria.", description: "Un site complet, profesional, generat de AI și publicat în propriul tău cont Vercel. Plătești o singură dată. Deții codul. Fără chirie lunară." },
  banner: { text: "insixlive este în beta privat — construim site-uri reale pentru afaceri mici din toată UE.", cta: "Înscrie-te pe listă" },
  navLinks: [["#how", "Cum funcționează"], ["#examples", "Exemple"], ["#pricing", "Prețuri"], ["#faq", "Întrebări"]],
  signIn: "Autentificare",
  dashboardLabel: "Dashboard",
  getStarted: "Începe acum",
  hero: {
    headline1: "Site-uri profesionale.",
    headlineLead: "Publicate în ",
    cycleWords: ["contul tău.", "domeniul tău.", "codul tău.", "afacerea ta."],
    lead: "Descrie afacerea. AI generează site-ul. Publicat în propriul tău cont Vercel — șase minute, plată unică, al tău pentru totdeauna.",
    emailPlaceholder: "tu@afacereata.ro",
    submitLabel: "Începe acum",
    liveIn: "● Online în ~6 minute",
    oneTimeFrom: "● 59,99 € plată unică",
    previewLabel: "previzualizare produs — site live",
    deployReady: "deploy · gata",
  },
  problem: {
    eyebrow: "Capcana",
    heading: [
      [{ t: "Constructorii " }, { t: "te blochează.", c: "#64CEFB", w: 600 }],
      [{ t: "Agențiile cer " }, { t: "mii de euro.", c: "#a78bfa", w: 600 }],
    ],
    lead: [
      { t: "Contul tău de Instagram e online non-stop — și " },
      { t: "nu plătești", c: "#4ade80", w: 600 },
      { t: " ca să rămână acolo. Site-ul tău poate fi la fel. Alții îți iau bani lunar ca să țină pagina online: e " },
      { t: "schemă, e golănie", c: "#a78bfa", w: 600 },
      { t: ". Un site profesional nu ar trebui să implice abonament lunar sau retainer de agenție. Afacerea ta merită " },
      { t: "cod real", c: "#4ade80", w: 600 },
      { t: " pe care îl deții complet — nu chirie." },
    ],
    rows: [
      {
        lead: [{ t: "Ca pe Instagram" }],
        key: [{ t: "Online mereu — fără taxă lunară ca să existe." }],
      },
      {
        lead: [{ t: "Site-ul tău" }],
        key: [{ t: "Plătești o dată, rămâne online." }],
      },
      {
        lead: [{ t: "Ce fac alții" }],
        key: [
          { t: "Bani în fiecare lună — " },
          { t: "schemă pură", c: "#a78bfa", w: 600 },
          { t: "." },
        ],
      },
      {
        lead: [{ t: "Ce primești aici" }],
        key: [
          { t: "Cod real, al tău. Fără blocare, fără " },
          { t: "chirie", c: "#a78bfa", w: 600 },
          { t: "." },
        ],
      },
    ],
  },
  how: {
    eyebrow: "De la prompt la online",
    heading: [
      [{ t: "Șase pași." }],
      [{ t: "Un site " }, { t: "online.", c: ACCENT.green, w: 600 }],
    ],
    lead: [
      { t: "Constructorii durează zile. Agențiile durează săptămâni. Noi durăm " },
      { t: "șase minute", c: ACCENT.cyan, w: 600 },
      { t: "." },
    ],
    steps: [
      ["Descrie-ți afacerea", "Nume, servicii, locație, public și ton."],
      ["Alege stilul", "Culori, tipografie, layout — estetica ta."],
      ["Selectează paginile", "Acasă, Despre, Servicii, Contact, Programări."],
      ["Confirmă brieful", "Verifică planul înainte să înceapă generarea."],
      ["Plătești o dată", "Plată prin Stripe. Fără taxe recurente."],
      ["Intră online", "Generat și publicat pe Vercel-ul tău — în ~6 minute."],
    ],
    liveStepTitle: [{ t: "Intră " }, { t: "online", c: ACCENT.green, w: 600 }],
    liveBadge: "Online",
  },
  examples: {
    eyebrow: "Lucrări selectate",
    heading: [
      [{ t: "Site-uri construite" }],
      [{ t: "cu " }, { t: "insixlive.", c: ACCENT.cyan, w: 600 }],
    ],
    viewAll: "Vezi toate șabloanele",
    previewTag: "site live",
    decorativeTag: "decorativ",
    decorText: ["Design care", "convertește vizitatori."],
    tiles: [
      { name: "Acme Plumbing", badges: ["Meserii & Servicii"] },
      { name: "Maria's Hair", badges: ["Frumusețe & Lifestyle"] },
      { name: "", badges: [] },
      { name: "Bistro Marin", badges: ["Alimentație & Ospitalitate"] },
      { name: "Lia · Photo", badges: ["Portofoliu & Creativ"] },
      { name: "Forge Fitness", badges: ["Sănătate & Fitness"] },
    ],
  },
  stats: [
    ["~6 min", "De la brief la un site live și publicat"],
    ["100%", "Proprietatea codului — fiecare fișier e al tău"],
    ["€0", "Taxe lunare după lansare. Plătești o dată, apoi gratuit."],
    ["€10", "Modificări la tarif fix — fără facturi surpriză"],
  ],
  ownership: {
    eyebrow: "Proprietate",
    heading: [
      [{ t: "Nu-ți închiriezi site-ul." }],
      [{ t: "Deții " }, { t: "fiecare linie.", c: ACCENT.green, w: 600 }],
    ],
    lead: [
      { t: "Majoritatea constructorilor îți țin afacerea pe " },
      { t: "platforma lor", c: ACCENT.purple, w: 600 },
      { t: ". insixlive publică cod Next.js în " },
      { t: "contul tău Vercel", c: ACCENT.cyan, w: 600 },
      { t: " — al tău să îl păstrezi, modifici sau muți." },
    ],
    badges: ["Contul tău Vercel", "Next.js standard", "Al tău pentru totdeauna"],
    repoLabel: "repo · acme-plumbing",
    repoFiles: "app/page.tsx · components/ · public/",
    deployLabel: "publicare",
    deployUrl: "acme-plumbing.vercel.app",
    readyBadge: "● Gata",
  },
  math: {
    eyebrow: "Prețuri",
    heading: "Cifrele vorbesc.",
    lead: "Agenție vs. insixlive — același rezultat, o fracțiune din cost. O plată, codul tău, Vercel-ul tău.",
    traditional: {
      colHead: "Site tradițional",
      price: "1.000 €+",
      priceSub: "în avans, apoi taxe lunare",
      rows: ["Săptămâni de discuții cu agenții", "Blocat într-o platformă închisă", "Orice modificare mică = factură", "Nu deții niciodată complet rezultatul"],
    },
    insixlive: {
      badge: "insixlive",
      pill: "Plată unică",
      price: "59,99 €",
      priceSub: "plată unică · găzduire gratuită pe Vercel",
      rows: ["Online în ~6 minute", "Publicat pe propriul tău Vercel", "Cod sursă complet în inbox-ul tău", "Fără abonament, niciodată"],
    },
  },
  pricing: {
    eyebrow: "Prețuri",
    heading: [
      [{ t: "Plată unică.", c: ACCENT.green, w: 600 }],
      [{ t: "Fără " }, { t: "chirie lunară", c: ACCENT.purple, w: 600 }, { t: " pentru site." }],
    ],
    lead: [
      { t: "Același rezultat ca la agenție, o fracțiune din cost. " },
      { t: "O plată", c: ACCENT.green, w: 600 },
      { t: ", codul tău, Vercel-ul tău." },
    ],
    popularBadge: "Cel mai popular",
    plans: [
      { name: "Site", price: "59,99 €", tag: "Site complet. Fără modificări incluse.", items: ["Site profesional generat de AI", "Publicat în contul tău Vercel", "Deținerea întregului cod sursă", "Responsive · SSL · pregătit pentru domeniu"], muted: "0 modificări gratuite", cta: "Începe acum", after: "10,00 € per modificare după lansare", featured: true },
      { name: "Pro", price: "69,99 €", tag: "Vreau să ajustez site-ul.", items: ["Tot ce e în Site", "5 modificări gratuite incluse", "Urmărirea modificărilor în panou", "Suport prioritar pe email", "Ideal dacă te aștepți la schimbări"], cta: "Alege Pro", after: "10,00 € per modificare după primele 5" },
      { name: "Premium", price: "89,99 €", tag: "Spațiu maxim de ajustare.", items: ["Tot ce e în Pro", "15 modificări gratuite incluse", "Coadă prioritară de generare", "Apel de onboarding 1:1 (opțional)", "Pentru afaceri în creștere"], cta: "Alege Premium", after: "10,00 € per modificare după primele 15" },
    ],
    note: { badge: "Notă", text: "Ai nevoie de o singură modificare mai târziu? Solicită modificări din panoul tău pentru 10,00 € per modificare. Domeniile personalizate nu sunt incluse și costă de obicei 12–30 €/an." },
  },
  domains: {
    eyebrow: "Domenii",
    heading: [
      [{ t: "Folosește " }, { t: "propriul tău domeniu.", c: ACCENT.cyan, w: 600 }],
      [{ t: "Sau cumpără unul separat." }],
    ],
    lead: [
      { t: "Site-ul tău " },
      { t: "intră online", c: ACCENT.green, w: 600 },
      { t: " întâi pe un URL Vercel. Apoi conectezi un domeniu precum " },
      { t: "afacereata.ro", c: ACCENT.cyan, w: 600 },
      { t: " — unul pe care îl deții deja sau îl cumperi de la orice registrar." },
    ],
    exampleDomain: "afacereata.ro",
    registrars: ["GoDaddy", "Namecheap", "Porkbun", "Cloudflare"],
    bar1: { domain: "acme-plumbing.vercel.app", status: "● Online" },
    bar2: { domain: "acmeplumbing.com", status: "● Conectat" },
  },
  proof: {
    eyebrow: "Clienți",
    heading: [
      [{ t: "Construit pentru micii antreprenori" }],
      [{ t: "fără " }, { t: "prețuri de agenție", c: ACCENT.purple, w: 600 }, { t: "." }],
    ],
    lead: "Testat cu saloane, meseriași, clinici și freelanceri din toată UE în timpul beta-ului privat.",
    testimonials: [
      { initials: "BM", name: "Bogdan Mureșan", biz: "Mureșan Electric · Cluj-Napoca · Pro", quote: "Duminică seara am scris că fac instalații electrice în Cluj. Luni dimineața am trimis link-ul la primii trei clienți. Niciunul nu a crezut că m-a costat sub 100 de euro." },
      { initials: "IC", name: "Ioana Constantin", biz: "Ioana Beauty Studio · București · Basic", quote: "Plăteam 18 € pe lună pe Wix de trei ani. Nici nu mai știam de ce. Cu insixlive am plătit o dată și am primit codul — al meu, nu al lor. Acum fac calculul și mă enervez că n-am făcut asta mai devreme." },
      { initials: "RV", name: "Dr. Radu Vlad", biz: "Cabinet Veterinar Vlad · Timișoara · Premium", quote: "Voiam ceva serios, nu un șablon ieftin. Prima variantă generată arăta mai bine decât oferta agenției la care ceruseră 2.000 €. Am cerut patru modificări și am lansat." },
    ],
  },
  faq: {
    eyebrow: "Întrebări frecvente",
    heading: [{ t: "Întrebări cu " }, { t: "răspunsuri", c: ACCENT.cyan, w: 600 }, { t: "." }],
    lead: [{ t: "Tot ce trebuie să știi " }, { t: "înainte să începi", c: ACCENT.green, w: 600 }, { t: "." }],
    items: [
      ["Trebuie să știu să programez?", "Nu. Îți descrii afacerea în limbaj simplu. Noi generăm site-ul, îl publicăm, iar tu îl poți edita mai târziu din panoul tău sau direct în cod."],
      ["Cine deține site-ul?", "Tu. Codul e al tău, proiectul Vercel e în contul tău, iar domeniul (dacă conectezi unul) îți aparține."],
      ["Există vreun abonament?", "Niciun abonament pentru site-ul generat. Plătești o singură dată. Găzduirea Vercel este gratuită pentru majoritatea site-urilor mici. Domeniile personalizate se plătesc separat unui registrar."],
      ["Ce se întâmplă după ce plătesc?", "Generăm site-ul, îl publicăm pe Vercel-ul tău și îți trimitem URL-ul. Tot procesul durează aproximativ șase minute."],
      ["Pot să conectez propriul meu domeniu?", "Da. Conectează un domeniu de la orice registrar (GoDaddy, Namecheap, Porkbun, Cloudflare etc.) sau cumpără unul nou separat."],
      ["Pot să mă mut de pe Vercel?", "Da. Codul este un proiect Next.js standard — găzduiește-l oriunde rulează Node sau site-uri statice."],
    ],
  },
  final: {
    eyebrow: "Începe acum",
    heading: [
      { t: "Peste șase minute, site-ul tău este " },
      { t: "online", c: ACCENT.green, w: 600 },
      { t: "." },
    ],
    lead: [
      { t: "De la brief la publicat — AI generează codul și îl trimite în " },
      { t: "contul tău", c: ACCENT.cyan, w: 600 },
      { t: "." },
    ],
    secondaryCta: "Vezi prețurile",
  },
  footer: {
    blurb: "Site-uri reale, generate de AI, publicate în contul tău. Deține-le — nu le închiria.",
    groups: [
      {
        title: "Produs",
        links: [
          { href: "#how", label: "Cum funcționează" },
          { href: "#examples", label: "Exemple" },
          { href: "#pricing", label: "Prețuri" },
          { href: "#faq", label: "Întrebări" },
        ],
      },
      {
        title: "Legal",
        links: [
          { href: "/privacy?lang=ro", label: "Confidențialitate" },
          { href: "/terms?lang=ro", label: "Termeni" },
          { href: "/email-preferences", label: "Preferințe email" },
        ],
      },
    ],
    accountTitle: "Cont",
    createSite: "Creează-ți site-ul",
    supportTitle: "Suport",
    supportEmail: "support@insixlive.com",
    copyright: "© 2026 insixlive. Deține-ți site-ul. Nu-l închiria.",
    builtWith: "Construit cu Next.js · Publicat pe Vercel",
  },
};
