// ─── Translatable copy for the Awesomic homepage (EN + RO) ────────────────
// Source design: claude.ai/design/p/019e130a-b156-7a53-9abe-2feed797f07c

export type HomeCopy = {
  meta: { title: string; description: string };
  banner: { text: string; cta: string };
  navLinks: [string, string][];
  signIn: string;
  dashboardLabel: string;
  getStarted: string;
  hero: {
    headline1: string;
    headlineLead: string;
    cycleWords: string[];
    lead: string;
    emailPlaceholder: string;
    submitLabel: string;
    liveIn: string;
    oneTimeFrom: string;
    previewLabel: string;
    deployReady: string;
  };
  problem: { eyebrow: string; heading: [string, string]; lead: string; rows: [string, string][] };
  solution: { eyebrow: string; heading: [string, string]; lead: string; features: { t: string; b: string }[] };
  how: { eyebrow: string; heading: [string, string]; lead: string; steps: [string, string][]; liveBadge: string };
  examples: {
    eyebrow: string;
    heading: [string, string];
    viewAll: string;
    previewTag: string;
    decorativeTag: string;
    decorText: [string, string];
    tiles: { name: string; badges?: string[] }[];
  };
  stats: [string, string][];
  ownership: {
    eyebrow: string;
    heading: [string, string];
    lead: string;
    badges: string[];
    repoLabel: string;
    repoFiles: string;
    deployLabel: string;
    deployUrl: string;
    readyBadge: string;
  };
  math: {
    eyebrow: string;
    heading: string;
    lead: string;
    traditional: { colHead: string; price: string; priceSub: string; rows: string[] };
    insixlive: { badge: string; price: string; priceSub: string; rows: string[] };
  };
  pricing: {
    eyebrow: string;
    heading: [string, string];
    popularBadge: string;
    plans: { name: string; price: string; tag: string; items: string[]; muted?: string; cta: string; after: string; featured?: boolean }[];
    note: { badge: string; text: string };
  };
  domains: {
    eyebrow: string;
    heading: [string, string];
    lead: string;
    exampleDomain: string;
    registrars: string[];
    bar1: { domain: string; status: string };
    bar2: { domain: string; status: string };
  };
  proof: {
    eyebrow: string;
    heading: [string, string];
    lead: string;
    testimonials: { initials: string; name: string; biz: string; quote: string }[];
  };
  faq: { eyebrow: string; heading: string; lead: string; items: [string, string][] };
  final: { eyebrow: string; heading: string; lead: string; secondaryCta: string };
  footer: {
    blurb: string;
    productHeader: string;
    companyHeader: string;
    startHeader: string;
    customers: string;
    waitlist: string;
    whyInsixlive: string;
    createSite: string;
    copyright: string;
    builtWith: string;
  };
};

export const EN: HomeCopy = {
  meta: { title: "insixlive — Own your website. Don't rent it.", description: "A complete, professional website generated by AI and deployed to your own Vercel account. Pay once. Own the code. No monthly rent." },
  banner: { text: "insixlive is in private beta — building real websites for small businesses across the EU.", cta: "Join the waitlist" },
  navLinks: [["#how", "How it works"], ["#examples", "Examples"], ["#pricing", "Pricing"], ["#faq", "FAQ"]],
  signIn: "Sign in",
  dashboardLabel: "Dashboard",
  getStarted: "Get started",
  hero: {
    headline1: "Professional websites.",
    headlineLead: "Deployed to ",
    cycleWords: ["your account.", "your domain.", "your code.", "your business."],
    lead: "Describe your business. AI generates the site. Deployed to your own Vercel account — six minutes, one-time payment, yours forever.",
    emailPlaceholder: "you@yourbusiness.com",
    submitLabel: "Get started",
    liveIn: "● Live in ~6 minutes",
    oneTimeFrom: "● One-time from €49.99",
    previewLabel: "product preview — live website",
    deployReady: "deploy · ready",
  },
  problem: {
    eyebrow: "The trap",
    heading: ["Agencies charge thousands.", "Builders lock you in."],
    lead: "A professional website shouldn't demand a monthly subscription or an agency retainer. Your business deserves real code you own outright — not rent.",
    rows: [
      ["No more", "weeks of back-and-forth with agencies."],
      ["No more", "paying rent to a closed platform."],
      ["No more", "extra invoices for minor changes."],
      ["No more", "code you never fully own."],
    ],
  },
  solution: {
    eyebrow: "The solution",
    heading: ["Real website. Generated by AI.", "Deployed to your account."],
    lead: "Describe your business. insixlive generates the site and deploys it directly to your own Vercel account. Pay once. No monthly fees. No lock-in.",
    features: [
      { t: "AI-generated site", b: "Professional copy, layout, and responsive design — written precisely for your business." },
      { t: "Your Vercel, not ours", b: "Your site runs in your own account — not inside a closed builder you can never leave." },
      { t: "Full code ownership", b: "Every file is yours. Modify it, move it, or hand it to a developer — forever." },
      { t: "One-time payment", b: "Pay once for the site. Vercel hosting stays free for most small businesses." },
      { t: "Custom domain ready", b: "Connect any domain you already own, or buy one separately." },
      { t: "Standard Next.js", b: "No proprietary builder — standard React deployed on the world's leading hosting platform." },
    ],
  },
  how: {
    eyebrow: "From prompt to live",
    heading: ["Six steps.", "One live website."],
    lead: "Builders take days. Agencies take weeks. We take six minutes.",
    steps: [
      ["Describe your business", "Name, services, location, audience, and tone."],
      ["Choose the style", "Colors, typography, layout — your aesthetic."],
      ["Select your pages", "Home, About, Services, Contact, Booking."],
      ["Confirm the brief", "Review the plan before generation begins."],
      ["Pay once", "Stripe checkout. No recurring charge."],
      ["Go live", "Generated and deployed to your Vercel — in ~6 minutes."],
    ],
    liveBadge: "Live",
  },
  examples: {
    eyebrow: "Selected work",
    heading: ["Websites built", "with insixlive."],
    viewAll: "View all templates",
    previewTag: "live site",
    decorativeTag: "decorative",
    decorText: ["Design that", "converts visitors."],
    tiles: [
      { name: "Acme Plumbing", badges: ["Trades & Services"] },
      { name: "Maria's Hair", badges: ["Beauty & Lifestyle"] },
      { name: "", badges: [] },
      { name: "Bistro Marin", badges: ["Food & Hospitality"] },
      { name: "Lia · Photo", badges: ["Portfolio & Creative"] },
      { name: "Forge Fitness", badges: ["Health & Fitness"] },
    ],
  },
  stats: [
    ["~6 min", "From brief to a live, deployed website"],
    ["100%", "Code ownership — every file is yours"],
    ["€0", "Monthly fees after launch. Pay once, then free."],
    ["€15", "Flat-rate edits — no surprise invoices"],
  ],
  ownership: {
    eyebrow: "Ownership",
    heading: ["You don't rent your website.", "You own every line."],
    lead: "Most builders keep your business inside their platform. insixlive deploys real Next.js code to your own Vercel account — yours to keep, modify, or move.",
    badges: ["Your Vercel account", "Standard Next.js", "Yours forever"],
    repoLabel: "repo · acme-plumbing",
    repoFiles: "app/page.tsx · components/ · public/",
    deployLabel: "deployment",
    deployUrl: "acme-plumbing.vercel.app",
    readyBadge: "● Ready",
  },
  math: {
    eyebrow: "The numbers",
    heading: "The numbers speak.",
    lead: "insixlive vs. the usual suspects. Pricing is illustrative — competitor plans change.",
    traditional: {
      colHead: "Traditional website",
      price: "€1,000+",
      priceSub: "upfront, then monthly fees",
      rows: ["Weeks of back-and-forth", "Locked inside a closed platform", "Every small change = an invoice", "You never fully own the result"],
    },
    insixlive: {
      badge: "insixlive",
      price: "from €49.99",
      priceSub: "one-time, then free",
      rows: ["Live in around 6 minutes", "Deployed to your own Vercel", "Full source code — every file", "No subscription, ever"],
    },
  },
  pricing: {
    eyebrow: "One-time pricing",
    heading: ["One-time pricing.", "No monthly website rent."],
    popularBadge: "Most popular",
    plans: [
      { name: "Basic", price: "€49.99", tag: "I just need a website.", items: ["AI-generated professional website", "Deployed to your Vercel account", "Full source code ownership", "Mobile-responsive · SSL · domain ready"], muted: "0 free edits", cta: "Get Basic", after: "€15 per edit after launch" },
      { name: "Pro", price: "€59.99", tag: "I want to refine my site.", items: ["Everything in Basic", "5 free edits included", "Edit tracking in your dashboard", "Best value for most businesses", "Priority email support"], cta: "Get Pro", after: "€15 per edit after the first 5", featured: true },
      { name: "Premium", price: "€79.99", tag: "I want room to adjust.", items: ["Everything in Pro", "15 free edits included", "Priority generation queue", "Best for evolving businesses", "1:1 onboarding call (optional)"], cta: "Get Premium", after: "€15 per edit after the first 15" },
    ],
    note: { badge: "Note", text: "Need a single change later? Request edits from your dashboard for €15 per change. Custom domains are not included and usually cost €12–30/year." },
  },
  domains: {
    eyebrow: "Domains",
    heading: ["Use your own domain.", "Or buy one separately."],
    lead: "Your generated website goes live first on a Vercel URL. Then connect a custom domain like yourbusiness.com — one you already own, or one you buy from any registrar.",
    exampleDomain: "yourbusiness.com",
    registrars: ["GoDaddy", "Namecheap", "Porkbun", "Cloudflare"],
    bar1: { domain: "acme-plumbing.vercel.app", status: "● Live" },
    bar2: { domain: "acmeplumbing.com", status: "● Connected" },
  },
  proof: {
    eyebrow: "Clients",
    heading: ["Built for small business owners", "who need real websites without agency prices."],
    lead: "Tested with salons, trades, clinics, and freelancers across the EU during private beta.",
    testimonials: [
      { initials: "ML", name: "Markus Lehmann", biz: "Acme Plumbing · Munich · Pro", quote: "I described the business in two sentences. Six minutes later I had a website I could send to the printer. No subscription, no monthly bill." },
      { initials: "MC", name: "Maria Coelho", biz: "Maria's Hair · Lisbon · Basic", quote: "My old site was on a builder I paid €18/month for. I rebuilt with insixlive and now I just own the code. The math is brutal in their favor." },
      { initials: "AK", name: "Dr. Anna Kohl", biz: "Kohl Dental · Berlin · Premium", quote: "I wanted a clean, calm, trustworthy site. The first draft was 80% there — three small edits and we shipped it." },
    ],
  },
  faq: {
    eyebrow: "FAQ",
    heading: "Questions answered.",
    lead: "Everything you need to know before you start.",
    items: [
      ["Do I need to know how to code?", "No. You describe your business in plain English. We generate the site, deploy it, and you can edit later through your dashboard or directly in the code."],
      ["Who owns the website?", "You do. The code is yours, the Vercel project is in your account, and the domain (if you connect one) belongs to you."],
      ["Is there a subscription?", "No subscription on the generated website. You pay once. Vercel hosting is free for most small sites. Custom domains are paid separately to a registrar."],
      ["What happens after I pay?", "We generate the site, push it to your Vercel, and send you the deploy URL. The whole flow takes around six minutes."],
      ["Can I connect my own domain?", "Yes. Connect a domain from any registrar (GoDaddy, Namecheap, Porkbun, Cloudflare, etc.) or buy a new one separately."],
      ["Can I move away from Vercel?", "Yes. The code is a standard Next.js project — host it anywhere that runs Node or static sites."],
    ],
  },
  final: {
    eyebrow: "Get started",
    heading: "Six minutes from now, your website is live.",
    lead: "Brief to deployed — AI generates your code and ships it to your account.",
    secondaryCta: "See pricing",
  },
  footer: {
    blurb: "Real websites, generated by AI, deployed to your account. Own it — don't rent it.",
    productHeader: "Product",
    companyHeader: "Company",
    startHeader: "Get started",
    customers: "Customers",
    waitlist: "Waitlist",
    whyInsixlive: "Why insixlive",
    createSite: "Create your site",
    copyright: "© 2026 insixlive. Own your website. Don't rent it.",
    builtWith: "Built with Next.js · Deployed on Vercel",
  },
};

export const RO: HomeCopy = {
  meta: { title: "insixlive — Deține-ți site-ul. Nu-l închiria.", description: "Un site complet, profesional, generat de AI și publicat în propriul tău cont Vercel. Plătești o singură dată. Deții codul. Fără chirie lunară." },
  banner: { text: "insixlive este în beta privat — construim site-uri reale pentru afaceri mici din toată UE.", cta: "Înscrie-te pe listă" },
  navLinks: [["#how", "Cum funcționează"], ["#examples", "Exemple"], ["#pricing", "Prețuri"], ["#faq", "Întrebări"]],
  signIn: "Autentificare",
  dashboardLabel: "Dashboard",
  getStarted: "Începe acum",
  hero: {
    headline1: "Site-uri profesionale.",
    headlineLead: "Publicate în ",
    cycleWords: ["contul tău.", "domeniul tău.", "codul tău.", "afacerea ta."],
    lead: "Descrie afacerea. AI generează site-ul. Publicat în propriul tău cont Vercel — șase minute, plată unică, al tău pentru totdeauna.",
    emailPlaceholder: "tu@afacereata.ro",
    submitLabel: "Începe acum",
    liveIn: "● Online în ~6 minute",
    oneTimeFrom: "● O singură plată de la 49,99 €",
    previewLabel: "previzualizare produs — site live",
    deployReady: "deploy · gata",
  },
  problem: {
    eyebrow: "Capcana",
    heading: ["Agențiile cer mii de euro.", "Constructorii te blochează."],
    lead: "Un site profesional nu ar trebui să implice un abonament lunar sau un retainer de agenție. Afacerea ta merită cod real pe care îl deții complet — nu chirie.",
    rows: [
      ["Nu mai", "săptămâni de discuții cu agențiile."],
      ["Nu mai", "plătești chirie unei platforme închise."],
      ["Nu mai", "facturi pentru modificări minore."],
      ["Nu mai", "cod pe care nu îl deții cu adevărat."],
    ],
  },
  solution: {
    eyebrow: "Soluția",
    heading: ["Site real. Generat de AI.", "Publicat în contul tău."],
    lead: "Descrie afacerea. insixlive generează site-ul și îl publică direct în contul tău Vercel. Plătești o dată. Fără taxe lunare. Fără blocare.",
    features: [
      { t: "Site generat de AI", b: "Texte profesionale, layout și design responsive — scrise precis pentru afacerea ta." },
      { t: "Vercel-ul tău, nu al nostru", b: "Site-ul tău rulează în propriul cont — nu într-un constructor închis din care nu poți pleca." },
      { t: "Cod complet în proprietatea ta", b: "Fiecare fișier e al tău. Modifică-l, mută-l sau dă-l unui dezvoltator — pentru totdeauna." },
      { t: "Plată unică", b: "Plătești o dată pentru site. Găzduirea Vercel rămâne gratuită pentru majoritatea afacerilor mici." },
      { t: "Pregătit pentru domeniu propriu", b: "Conectează orice domeniu pe care îl deții deja sau cumpără unul separat." },
      { t: "Next.js standard", b: "Fără constructor proprietar — React standard publicat pe cea mai performantă platformă de hosting." },
    ],
  },
  how: {
    eyebrow: "De la prompt la online",
    heading: ["Șase pași.", "Un site online."],
    lead: "Constructorii durează zile. Agențiile durează săptămâni. Noi durăm șase minute.",
    steps: [
      ["Descrie-ți afacerea", "Nume, servicii, locație, public și ton."],
      ["Alege stilul", "Culori, tipografie, layout — estetica ta."],
      ["Selectează paginile", "Acasă, Despre, Servicii, Contact, Programări."],
      ["Confirmă brieful", "Verifică planul înainte să înceapă generarea."],
      ["Plătești o dată", "Plată prin Stripe. Fără taxe recurente."],
      ["Intră online", "Generat și publicat pe Vercel-ul tău — în ~6 minute."],
    ],
    liveBadge: "Online",
  },
  examples: {
    eyebrow: "Lucrări selectate",
    heading: ["Site-uri construite", "cu insixlive."],
    viewAll: "Vezi toate șabloanele",
    previewTag: "site live",
    decorativeTag: "decorativ",
    decorText: ["Design care", "convertește vizitatori."],
    tiles: [
      { name: "Acme Plumbing", badges: ["Meserii & Servicii"] },
      { name: "Maria's Hair", badges: ["Frumusețe & Lifestyle"] },
      { name: "", badges: [] },
      { name: "Bistro Marin", badges: ["Alimentație & Ospitalitate"] },
      { name: "Lia · Photo", badges: ["Portofoliu & Creativ"] },
      { name: "Forge Fitness", badges: ["Sănătate & Fitness"] },
    ],
  },
  stats: [
    ["~6 min", "De la brief la un site live și publicat"],
    ["100%", "Proprietatea codului — fiecare fișier e al tău"],
    ["€0", "Taxe lunare după lansare. Plătești o dată, apoi gratuit."],
    ["€15", "Modificări la tarif fix — fără facturi surpriză"],
  ],
  ownership: {
    eyebrow: "Proprietate",
    heading: ["Nu-ți închiriezi site-ul.", "Deții fiecare linie."],
    lead: "Majoritatea constructorilor îți țin afacerea în platforma lor. insixlive publică cod real Next.js în propriul tău cont Vercel — al tău să îl păstrezi, modifici sau muți.",
    badges: ["Contul tău Vercel", "Next.js standard", "Al tău pentru totdeauna"],
    repoLabel: "repo · acme-plumbing",
    repoFiles: "app/page.tsx · components/ · public/",
    deployLabel: "publicare",
    deployUrl: "acme-plumbing.vercel.app",
    readyBadge: "● Gata",
  },
  math: {
    eyebrow: "Cifrele",
    heading: "Cifrele vorbesc.",
    lead: "insixlive vs. suspecții obișnuiți. Prețurile sunt orientative — planurile concurenței se schimbă.",
    traditional: {
      colHead: "Site tradițional",
      price: "€1,000+",
      priceSub: "în avans, apoi taxe lunare",
      rows: ["Săptămâni de discuții cu agenții", "Blocat într-o platformă închisă", "Orice modificare mică = factură", "Nu deții niciodată complet rezultatul"],
    },
    insixlive: {
      badge: "insixlive",
      price: "de la 49,99 €",
      priceSub: "o singură plată, apoi gratuit",
      rows: ["Online în aproximativ 6 minute", "Publicat pe propriul tău Vercel", "Cod sursă complet în inbox-ul tău", "Fără abonament, niciodată"],
    },
  },
  pricing: {
    eyebrow: "Plată unică",
    heading: ["Plată unică.", "Fără chirie lunară pentru site."],
    popularBadge: "Cel mai popular",
    plans: [
      { name: "Basic", price: "€49.99", tag: "Am nevoie doar de un site.", items: ["Site profesional generat de AI", "Publicat în contul tău Vercel", "Deținerea întregului cod sursă", "Responsive pe mobil · SSL · pregătit pentru domeniu"], muted: "0 modificări gratuite", cta: "Alege Basic", after: "15 € per modificare după lansare" },
      { name: "Pro", price: "€59.99", tag: "Vreau să-mi rafinez site-ul.", items: ["Tot ce e în Basic", "5 modificări gratuite incluse", "Urmărirea modificărilor în panoul tău", "Cel mai bun raport pentru majoritatea afacerilor", "Suport prioritar pe email"], cta: "Alege Pro", after: "15 € per modificare după primele 5", featured: true },
      { name: "Premium", price: "€79.99", tag: "Vreau spațiu de ajustare.", items: ["Tot ce e în Pro", "15 modificări gratuite incluse", "Coadă prioritară de generare", "Ideal pentru afaceri în creștere", "Apel de onboarding 1:1 (opțional)"], cta: "Alege Premium", after: "15 € per modificare după primele 15" },
    ],
    note: { badge: "Notă", text: "Ai nevoie de o singură modificare mai târziu? Solicită modificări din panoul tău pentru 15 € per modificare. Domeniile personalizate nu sunt incluse și costă de obicei 12–30 €/an." },
  },
  domains: {
    eyebrow: "Domenii",
    heading: ["Folosește propriul tău domeniu.", "Sau cumpără unul separat."],
    lead: "Site-ul tău generat intră întâi online pe un URL Vercel. Apoi conectezi un domeniu propriu precum afacereata.ro — unul pe care îl deții deja sau pe care îl cumperi de la orice registrar.",
    exampleDomain: "afacereata.ro",
    registrars: ["GoDaddy", "Namecheap", "Porkbun", "Cloudflare"],
    bar1: { domain: "acme-plumbing.vercel.app", status: "● Online" },
    bar2: { domain: "acmeplumbing.com", status: "● Conectat" },
  },
  proof: {
    eyebrow: "Clienți",
    heading: ["Construit pentru micii antreprenori", "care au nevoie de site-uri reale fără prețuri de agenție."],
    lead: "Testat cu saloane, meseriași, clinici și freelanceri din toată UE în timpul beta-ului privat.",
    testimonials: [
      { initials: "BM", name: "Bogdan Mureșan", biz: "Mureșan Electric · Cluj-Napoca · Pro", quote: "Duminică seara am scris că fac instalații electrice în Cluj. Luni dimineața am trimis link-ul la primii trei clienți. Niciunul nu a crezut că m-a costat sub 100 de euro." },
      { initials: "IC", name: "Ioana Constantin", biz: "Ioana Beauty Studio · București · Basic", quote: "Plăteam 18 € pe lună pe Wix de trei ani. Nici nu mai știam de ce. Cu insixlive am plătit o dată și am primit codul — al meu, nu al lor. Acum fac calculul și mă enervez că n-am făcut asta mai devreme." },
      { initials: "RV", name: "Dr. Radu Vlad", biz: "Cabinet Veterinar Vlad · Timișoara · Premium", quote: "Voiam ceva serios, nu un șablon ieftin. Prima variantă generată arăta mai bine decât oferta agenției la care ceruseră 2.000 €. Am cerut patru modificări și am lansat." },
    ],
  },
  faq: {
    eyebrow: "Întrebări frecvente",
    heading: "Întrebări cu răspunsuri.",
    lead: "Tot ce trebuie să știi înainte să începi.",
    items: [
      ["Trebuie să știu să programez?", "Nu. Îți descrii afacerea în limbaj simplu. Noi generăm site-ul, îl publicăm, iar tu îl poți edita mai târziu din panoul tău sau direct în cod."],
      ["Cine deține site-ul?", "Tu. Codul e al tău, proiectul Vercel e în contul tău, iar domeniul (dacă conectezi unul) îți aparține."],
      ["Există vreun abonament?", "Niciun abonament pentru site-ul generat. Plătești o singură dată. Găzduirea Vercel este gratuită pentru majoritatea site-urilor mici. Domeniile personalizate se plătesc separat unui registrar."],
      ["Ce se întâmplă după ce plătesc?", "Generăm site-ul, îl publicăm pe Vercel-ul tău și îți trimitem URL-ul. Tot procesul durează aproximativ șase minute."],
      ["Pot să conectez propriul meu domeniu?", "Da. Conectează un domeniu de la orice registrar (GoDaddy, Namecheap, Porkbun, Cloudflare etc.) sau cumpără unul nou separat."],
      ["Pot să mă mut de pe Vercel?", "Da. Codul este un proiect Next.js standard — găzduiește-l oriunde rulează Node sau site-uri statice."],
    ],
  },
  final: {
    eyebrow: "Începe acum",
    heading: "Peste șase minute, site-ul tău este online.",
    lead: "De la brief la publicat — AI îți generează codul și îl trimite în contul tău.",
    secondaryCta: "Vezi prețurile",
  },
  footer: {
    blurb: "Site-uri reale, generate de AI, publicate în contul tău. Deține-le — nu le închiria.",
    productHeader: "Produs",
    companyHeader: "Companie",
    startHeader: "Începe acum",
    customers: "Clienți",
    waitlist: "Listă de așteptare",
    whyInsixlive: "De ce insixlive",
    createSite: "Creează-ți site-ul",
    copyright: "© 2026 insixlive. Deține-ți site-ul. Nu-l închiria.",
    builtWith: "Construit cu Next.js · Publicat pe Vercel",
  },
};
