// ─── Translatable copy for the Awesomic homepage (EN + RO) ────────────────
// Source design: claude.ai/design/p/019e130a-b156-7a53-9abe-2feed797f07c

export type HomeCopy = {
  meta: { title: string; description: string };
  banner: { text: string; cta: string };
  navLinks: [string, string][];
  signIn: string;
  dashboardLabel: string;
  getStarted: string;
  hero: {
    headline1: string;
    headlineLead: string;
    cycleWords: string[];
    lead: string;
    emailPlaceholder: string;
    submitLabel: string;
    liveIn: string;
    oneTimeFrom: string;
    previewLabel: string;
    deployReady: string;
  };
  problem: { eyebrow: string; heading: [string, string]; lead: string; rows: [string, string][] };
  solution: { eyebrow: string; heading: [string, string]; lead: string; features: { t: string; b: string }[] };
  how: { eyebrow: string; heading: [string, string]; lead: string; steps: [string, string][]; liveBadge: string };
  examples: {
    eyebrow: string;
    heading: [string, string];
    viewAll: string;
    previewTag: string;
    decorativeTag: string;
    decorText: [string, string];
    tiles: { name: string; badges?: string[] }[];
  };
  stats: [string, string][];
  ownership: {
    eyebrow: string;
    heading: [string, string];
    lead: string;
    badges: string[];
    repoLabel: string;
    repoFiles: string;
    deployLabel: string;
    deployUrl: string;
    readyBadge: string;
  };
  math: {
    eyebrow: string;
    heading: string;
    lead: string;
    traditional: { colHead: string; price: string; priceSub: string; rows: string[] };
    insixlive: { badge: string; price: string; priceSub: string; rows: string[] };
  };
  pricing: {
    eyebrow: string;
    heading: [string, string];
    popularBadge: string;
    plans: { name: string; price: string; tag: string; items: string[]; muted?: string; cta: string; after: string; featured?: boolean }[];
    note: { badge: string; text: string };
  };
  domains: {
    eyebrow: string;
    heading: [string, string];
    lead: string;
    exampleDomain: string;
    registrars: string[];
    bar1: { domain: string; status: string };
    bar2: { domain: string; status: string };
  };
  proof: {
    eyebrow: string;
    heading: [string, string];
    lead: string;
    testimonials: { initials: string; name: string; biz: string; quote: string }[];
  };
  faq: { eyebrow: string; heading: string; lead: string; items: [string, string][] };
  final: { eyebrow: string; heading: string; lead: string; secondaryCta: string };
  footer: {
    blurb: string;
    productHeader: string;
    companyHeader: string;
    startHeader: string;
    customers: string;
    waitlist: string;
    whyInsixlive: string;
    createSite: string;
    copyright: string;
    builtWith: string;
  };
};

export const EN: HomeCopy = {
  meta: { title: "insixlive — Own your website. Don't rent it.", description: "A complete, professional website generated by AI and deployed to your own Vercel account. Pay once. Own the code. No monthly rent." },
  banner: { text: "insixlive is in private beta — building real websites for small businesses across the EU.", cta: "Join the waitlist" },
  navLinks: [["#how", "How it works"], ["#examples", "Examples"], ["#pricing", "Pricing"], ["#faq", "FAQ"]],
  signIn: "Sign in",
  dashboardLabel: "Dashboard",
  getStarted: "Get started",
  hero: {
    headline1: "Stop renting",
    headlineLead: "your ",
    cycleWords: ["website.", "homepage.", "storefront.", "brand."],
    lead: "A complete, professional website — generated by AI and deployed to your own account. You pay once. You own the code. No monthly rent, ever.",
    emailPlaceholder: "you@yourbusiness.com",
    submitLabel: "Get started",
    liveIn: "● Live in ~6 minutes",
    oneTimeFrom: "● One-time from €49.99",
    previewLabel: "product preview — generated site",
    deployReady: "deploy · ready",
  },
  problem: {
    eyebrow: "The rental trap",
    heading: ["Your business needs a website.", "Agencies know that."],
    lead: "A small business website shouldn't cost €1,000 upfront and a monthly fee just to stay online. You deserve a clean, professional site that works — and belongs to you.",
    rows: [
      ["Forget about", "weeks of back-and-forth."],
      ["Forget being", "locked inside a closed platform."],
      ["Forget", "extra invoices for small changes."],
      ["Forget", "never truly owning the result."],
    ],
  },
  solution: {
    eyebrow: "The solution",
    heading: ["A real website, generated by AI,", "deployed to your account."],
    lead: "insixlive turns your business description into a complete professional website. Answer a few questions, choose the style, pay once — and it's deployed to your own Vercel account.",
    features: [
      { t: "AI-generated website", b: "Professional copy, layout, sections and responsive design — all written for your business." },
      { t: "Deployed to your Vercel", b: "Your website lives in your own account — not inside a closed builder you can never leave." },
      { t: "Full source code ownership", b: "Keep it, edit it, move it, or hand it to a developer. Every file is yours, forever." },
      { t: "No monthly fees", b: "Pay once for the website. Vercel hosting stays free for most small sites." },
      { t: "Custom domain ready", b: "Connect a domain you already own, or buy one separately — entirely your call." },
      { t: "Built in real Next.js", b: "No proprietary builder. Standard React, Tailwind and a clean Vercel deploy." },
    ],
  },
  how: {
    eyebrow: "From prompt to live",
    heading: ["Six steps.", "One live website."],
    lead: "Most builders take days. Most freelancers take weeks. We take about six minutes.",
    steps: [
      ["Describe your business", "Name, services, audience, location, tone."],
      ["Choose the look", "Style, colors, typography, layout."],
      ["Pick your pages", "Home, About, Services, Contact, Booking…"],
      ["Review the brief", "Check the plan before generation starts."],
      ["Pay once", "Stripe checkout, no recurring charge."],
      ["Go live", "Generated, deployed to your Vercel, in ~6 min."],
    ],
    liveBadge: "Live",
  },
  examples: {
    eyebrow: "Shipped sites",
    heading: ["Websites built", "with insixlive."],
    viewAll: "View all examples",
    previewTag: "screenshot",
    decorativeTag: "decorative",
    decorText: ["Design that", "books clients."],
    tiles: [
      { name: "Acme Plumbing", badges: ["24/7 Emergency", "3 pages"] },
      { name: "Maria's Hair", badges: ["Salon · Munich", "Booking"] },
      { name: "", badges: [] },
      { name: "Bistro Marin", badges: ["Restaurant", "Reservations"] },
      { name: "Lia · Photo", badges: ["Wedding portfolio"] },
      { name: "Forge Fitness", badges: ["Coach", "Programs"] },
    ],
  },
  stats: [
    ["~6 min", "From prompt to a live, deployed website"],
    ["100%", "Source code ownership — every file is yours"],
    ["€0", "Monthly website rent. Pay once, then free"],
    ["€15", "Flat per edit after launch — no surprise invoices"],
  ],
  ownership: {
    eyebrow: "Ownership",
    heading: ["You don't rent your website.", "You own it."],
    lead: "Most website builders keep your business locked inside their platform. insixlive gives you a real website, deployed to your own account, with code you keep forever.",
    badges: ["Your Vercel account", "Standard Next.js", "Yours forever"],
    repoLabel: "repo · acme-plumbing",
    repoFiles: "app/page.tsx · components/ · public/",
    deployLabel: "deployment",
    deployUrl: "acme-plumbing.vercel.app",
    readyBadge: "● Ready",
  },
  math: {
    eyebrow: "The math",
    heading: "The math is simple.",
    lead: "insixlive vs. the usual suspects. Pricing is illustrative — competitor plans change.",
    traditional: {
      colHead: "Traditional website",
      price: "€1,000+",
      priceSub: "upfront, plus monthly fees",
      rows: ["Weeks of back-and-forth", "Locked inside a closed platform", "Small changes = extra invoices", "You don't fully own the result"],
    },
    insixlive: {
      badge: "insixlive",
      price: "from €49.99",
      priceSub: "one-time, then free",
      rows: ["Live in around 6 minutes", "Deployed to your own Vercel", "Full source code in your inbox", "No subscription, ever"],
    },
  },
  pricing: {
    eyebrow: "One-time pricing",
    heading: ["One-time pricing.", "No monthly website rent."],
    popularBadge: "Most popular",
    plans: [
      { name: "Basic", price: "€49.99", tag: "I just need a website.", items: ["AI-generated professional website", "Deployed to your Vercel account", "Full source code ownership", "Mobile-responsive · SSL · domain ready"], muted: "0 free edits", cta: "Get Basic", after: "€15 per edit after launch" },
      { name: "Pro", price: "€59.99", tag: "I want to refine my site.", items: ["Everything in Basic", "5 free edits included", "Edit tracking in your dashboard", "Best value for most businesses", "Priority email support"], cta: "Get Pro", after: "€15 per edit after the first 5", featured: true },
      { name: "Premium", price: "€79.99", tag: "I want room to adjust.", items: ["Everything in Pro", "15 free edits included", "Priority generation queue", "Best for evolving businesses", "1:1 onboarding call (optional)"], cta: "Get Premium", after: "€15 per edit after the first 15" },
    ],
    note: { badge: "Note", text: "Need a single change later? Request edits from your dashboard for €15 per change. Custom domains are not included and usually cost €12–30/year." },
  },
  domains: {
    eyebrow: "Domains",
    heading: ["Use your own domain.", "Or buy one separately."],
    lead: "Your generated website goes live first on a Vercel URL. Then connect a custom domain like yourbusiness.com — one you already own, or one you buy from any registrar.",
    exampleDomain: "yourbusiness.com",
    registrars: ["GoDaddy", "Namecheap", "Porkbun", "Cloudflare"],
    bar1: { domain: "acme-plumbing.vercel.app", status: "● Live" },
    bar2: { domain: "acmeplumbing.com", status: "● Connected" },
  },
  proof: {
    eyebrow: "Real businesses",
    heading: ["Built for small business owners", "who need a real website without agency prices."],
    lead: "Tested with salons, trades, clinics and freelancers across the EU during private beta.",
    testimonials: [
      { initials: "ML", name: "Markus Lehmann", biz: "Acme Plumbing · Munich · Pro", quote: "I described the business in two sentences. Six minutes later I had a website I could send to the printer. No subscription, no monthly bill." },
      { initials: "MC", name: "Maria Coelho", biz: "Maria's Hair · Lisbon · Basic", quote: "My old site was on a builder I paid €18/month for. I rebuilt with insixlive and now I just own the code. The math is brutal in their favor." },
      { initials: "AK", name: "Dr. Anna Kohl", biz: "Kohl Dental · Berlin · Premium", quote: "I wanted a clean, calm, trustworthy site. The first draft was 80% there — three small edits and we shipped it." },
    ],
  },
  faq: {
    eyebrow: "FAQ",
    heading: "Common questions.",
    lead: "The short version. Everything you need before you start.",
    items: [
      ["Do I need to know how to code?", "No. You describe your business in plain English. We generate the site, deploy it, and you can edit later through your dashboard or directly in the code."],
      ["Who owns the website?", "You do. The code is yours, the Vercel project is in your account, and the domain (if you connect one) belongs to you."],
      ["Is there a subscription?", "No subscription on the generated website. You pay once. Vercel hosting is free for most small sites. Custom domains are paid separately to a registrar."],
      ["What happens after I pay?", "We generate the site, push it to your Vercel, and send you the deploy URL. The whole flow takes around six minutes."],
      ["Can I connect my own domain?", "Yes. Connect a domain from any registrar (GoDaddy, Namecheap, Porkbun, Cloudflare, etc.) or buy a new one separately."],
      ["Can I move away from Vercel?", "Yes. The code is a standard Next.js project — host it anywhere that runs Node or static sites."],
    ],
  },
  final: {
    eyebrow: "Six minutes",
    heading: "Six minutes from now, your website could be live.",
    lead: "Describe your business, choose the look, pay once. We generate it and deploy it to your own account.",
    secondaryCta: "See pricing",
  },
  footer: {
    blurb: "A complete website, generated by AI and deployed to your own account. Own it — don't rent it.",
    productHeader: "Product",
    companyHeader: "Company",
    startHeader: "Get started",
    customers: "Customers",
    waitlist: "Waitlist",
    whyInsixlive: "Why insixlive",
    createSite: "Create your site",
    copyright: "© 2026 insixlive. Own your website. Don't rent it.",
    builtWith: "Built with Next.js · Deployed on Vercel",
  },
};

export const RO: HomeCopy = {
  meta: { title: "insixlive — Deține-ți site-ul. Nu-l închiria.", description: "Un site complet, profesional, generat de AI și publicat în propriul tău cont Vercel. Plătești o singură dată. Deții codul. Fără chirie lunară." },
  banner: { text: "insixlive este în beta privat — construim site-uri reale pentru afaceri mici din toată UE.", cta: "Înscrie-te pe listă" },
  navLinks: [["#how", "Cum funcționează"], ["#examples", "Exemple"], ["#pricing", "Prețuri"], ["#faq", "Întrebări"]],
  signIn: "Autentificare",
  dashboardLabel: "Dashboard",
  getStarted: "Începe acum",
  hero: {
    headline1: "Nu mai închiria",
    headlineLead: "",
    cycleWords: ["site-ul tău.", "pagina ta.", "magazinul tău.", "brandul tău."],
    lead: "Un site complet, profesional — generat de AI și publicat în propriul tău cont. Plătești o singură dată. Deții codul. Fără chirie lunară, niciodată.",
    emailPlaceholder: "tu@afacereata.ro",
    submitLabel: "Începe acum",
    liveIn: "● Online în ~6 minute",
    oneTimeFrom: "● O singură plată de la 49,99 €",
    previewLabel: "previzualizare produs — site generat",
    deployReady: "deploy · gata",
  },
  problem: {
    eyebrow: "Capcana chiriei",
    heading: ["Afacerea ta are nevoie de un site.", "Agențiile știu asta."],
    lead: "Un site pentru o afacere mică nu ar trebui să coste 1.000 € în avans plus o taxă lunară doar ca să rămână online. Meriți un site curat, profesional, care funcționează — și care îți aparține.",
    rows: [
      ["Uită de", "săptămânile de discuții dus-întors."],
      ["Uită că ești", "blocat într-o platformă închisă."],
      ["Uită de", "facturile pentru modificări mici."],
      ["Uită", "că nu deții niciodată cu adevărat rezultatul."],
    ],
  },
  solution: {
    eyebrow: "Soluția",
    heading: ["Un site real, generat de AI,", "publicat în contul tău."],
    lead: "insixlive transformă descrierea afacerii tale într-un site profesional complet. Răspunzi la câteva întrebări, alegi stilul, plătești o dată — și e publicat în propriul tău cont Vercel.",
    features: [
      { t: "Site generat de AI", b: "Texte profesionale, layout, secțiuni și design responsive — toate scrise pentru afacerea ta." },
      { t: "Publicat pe Vercel-ul tău", b: "Site-ul tău trăiește în propriul cont — nu într-un constructor închis din care nu poți pleca." },
      { t: "Deții întreg codul sursă", b: "Păstrează-l, editează-l, mută-l sau dă-l unui dezvoltator. Fiecare fișier e al tău, pentru totdeauna." },
      { t: "Fără taxe lunare", b: "Plătești o dată pentru site. Găzduirea Vercel rămâne gratuită pentru majoritatea site-urilor mici." },
      { t: "Pregătit pentru domeniu propriu", b: "Conectează un domeniu pe care îl deții deja sau cumpără unul separat — alegerea îți aparține." },
      { t: "Construit în Next.js real", b: "Fără constructor proprietar. React standard, Tailwind și un deploy curat pe Vercel." },
    ],
  },
  how: {
    eyebrow: "De la prompt la online",
    heading: ["Șase pași.", "Un site online."],
    lead: "Majoritatea constructorilor durează zile. Majoritatea freelancerilor durează săptămâni. Noi durăm aproximativ șase minute.",
    steps: [
      ["Descrie-ți afacerea", "Nume, servicii, public, locație, ton."],
      ["Alege aspectul", "Stil, culori, tipografie, layout."],
      ["Alege paginile", "Acasă, Despre, Servicii, Contact, Programări…"],
      ["Verifică brieful", "Verifică planul înainte să înceapă generarea."],
      ["Plătești o dată", "Plată prin Stripe, fără taxe recurente."],
      ["Intră online", "Generat, publicat pe Vercel-ul tău, în ~6 min."],
    ],
    liveBadge: "Online",
  },
  examples: {
    eyebrow: "Site-uri lansate",
    heading: ["Site-uri construite", "cu insixlive."],
    viewAll: "Vezi toate exemplele",
    previewTag: "captură",
    decorativeTag: "decorativ",
    decorText: ["Design care", "aduce clienți."],
    tiles: [
      { name: "Acme Plumbing", badges: ["Urgențe 24/7", "3 pagini"] },
      { name: "Maria's Hair", badges: ["Salon · München", "Programări"] },
      { name: "", badges: [] },
      { name: "Bistro Marin", badges: ["Restaurant", "Rezervări"] },
      { name: "Lia · Photo", badges: ["Portofoliu de nuntă"] },
      { name: "Forge Fitness", badges: ["Antrenor", "Programe"] },
    ],
  },
  stats: [
    ["~6 min", "De la prompt la un site publicat și online"],
    ["100%", "Deținerea codului sursă — fiecare fișier e al tău"],
    ["€0", "Chirie lunară pentru site. Plătești o dată, apoi gratuit"],
    ["€15", "Tarif fix per modificare după lansare — fără facturi surpriză"],
  ],
  ownership: {
    eyebrow: "Proprietate",
    heading: ["Nu-ți închiriezi site-ul.", "Îl deții."],
    lead: "Majoritatea constructorilor de site-uri îți țin afacerea blocată în platforma lor. insixlive îți oferă un site real, publicat în propriul tău cont, cu cod pe care îl păstrezi pentru totdeauna.",
    badges: ["Contul tău Vercel", "Next.js standard", "Al tău pentru totdeauna"],
    repoLabel: "repo · acme-plumbing",
    repoFiles: "app/page.tsx · components/ · public/",
    deployLabel: "publicare",
    deployUrl: "acme-plumbing.vercel.app",
    readyBadge: "● Gata",
  },
  math: {
    eyebrow: "Calculul",
    heading: "Calculul e simplu.",
    lead: "insixlive vs. suspecții obișnuiți. Prețurile sunt orientative — planurile concurenței se schimbă.",
    traditional: {
      colHead: "Site tradițional",
      price: "€1,000+",
      priceSub: "în avans, plus taxe lunare",
      rows: ["Săptămâni de discuții dus-întors", "Blocat într-o platformă închisă", "Modificări mici = facturi suplimentare", "Nu deții complet rezultatul"],
    },
    insixlive: {
      badge: "insixlive",
      price: "de la 49,99 €",
      priceSub: "o singură plată, apoi gratuit",
      rows: ["Online în aproximativ 6 minute", "Publicat pe propriul tău Vercel", "Cod sursă complet în inbox-ul tău", "Fără abonament, niciodată"],
    },
  },
  pricing: {
    eyebrow: "Plată unică",
    heading: ["Plată unică.", "Fără chirie lunară pentru site."],
    popularBadge: "Cel mai popular",
    plans: [
      { name: "Basic", price: "€49.99", tag: "Am nevoie doar de un site.", items: ["Site profesional generat de AI", "Publicat în contul tău Vercel", "Deținerea întregului cod sursă", "Responsive pe mobil · SSL · pregătit pentru domeniu"], muted: "0 modificări gratuite", cta: "Alege Basic", after: "15 € per modificare după lansare" },
      { name: "Pro", price: "€59.99", tag: "Vreau să-mi rafinez site-ul.", items: ["Tot ce e în Basic", "5 modificări gratuite incluse", "Urmărirea modificărilor în panoul tău", "Cel mai bun raport pentru majoritatea afacerilor", "Suport prioritar pe email"], cta: "Alege Pro", after: "15 € per modificare după primele 5", featured: true },
      { name: "Premium", price: "€79.99", tag: "Vreau spațiu de ajustare.", items: ["Tot ce e în Pro", "15 modificări gratuite incluse", "Coadă prioritară de generare", "Ideal pentru afaceri în creștere", "Apel de onboarding 1:1 (opțional)"], cta: "Alege Premium", after: "15 € per modificare după primele 15" },
    ],
    note: { badge: "Notă", text: "Ai nevoie de o singură modificare mai târziu? Solicită modificări din panoul tău pentru 15 € per modificare. Domeniile personalizate nu sunt incluse și costă de obicei 12–30 €/an." },
  },
  domains: {
    eyebrow: "Domenii",
    heading: ["Folosește propriul tău domeniu.", "Sau cumpără unul separat."],
    lead: "Site-ul tău generat intră întâi online pe un URL Vercel. Apoi conectezi un domeniu propriu precum afacereata.ro — unul pe care îl deții deja sau pe care îl cumperi de la orice registrar.",
    exampleDomain: "afacereata.ro",
    registrars: ["GoDaddy", "Namecheap", "Porkbun", "Cloudflare"],
    bar1: { domain: "acme-plumbing.vercel.app", status: "● Online" },
    bar2: { domain: "acmeplumbing.com", status: "● Conectat" },
  },
  proof: {
    eyebrow: "Afaceri reale",
    heading: ["Construit pentru micii antreprenori", "care au nevoie de un site real fără prețuri de agenție."],
    lead: "Testat cu saloane, meseriași, clinici și freelanceri din toată UE în timpul beta-ului privat.",
    testimonials: [
      { initials: "ML", name: "Markus Lehmann", biz: "Acme Plumbing · Munich · Pro", quote: "Am descris afacerea în două propoziții. Șase minute mai târziu aveam un site pe care îl puteam trimite la tipar. Fără abonament, fără factură lunară." },
      { initials: "MC", name: "Maria Coelho", biz: "Maria's Hair · Lisbon · Basic", quote: "Vechiul meu site era pe un constructor pentru care plăteam 18 €/lună. L-am refăcut cu insixlive și acum pur și simplu dețin codul. Calculul e brutal în favoarea lor." },
      { initials: "AK", name: "Dr. Anna Kohl", biz: "Kohl Dental · Berlin · Premium", quote: "Voiam un site curat, calm și de încredere. Prima variantă era 80% gata — trei modificări mici și l-am lansat." },
    ],
  },
  faq: {
    eyebrow: "Întrebări frecvente",
    heading: "Întrebări frecvente.",
    lead: "Pe scurt. Tot ce ai nevoie înainte să începi.",
    items: [
      ["Trebuie să știu să programez?", "Nu. Îți descrii afacerea în limbaj simplu. Noi generăm site-ul, îl publicăm, iar tu îl poți edita mai târziu din panoul tău sau direct în cod."],
      ["Cine deține site-ul?", "Tu. Codul e al tău, proiectul Vercel e în contul tău, iar domeniul (dacă conectezi unul) îți aparține."],
      ["Există vreun abonament?", "Niciun abonament pentru site-ul generat. Plătești o singură dată. Găzduirea Vercel este gratuită pentru majoritatea site-urilor mici. Domeniile personalizate se plătesc separat unui registrar."],
      ["Ce se întâmplă după ce plătesc?", "Generăm site-ul, îl publicăm pe Vercel-ul tău și îți trimitem URL-ul. Tot procesul durează aproximativ șase minute."],
      ["Pot să conectez propriul meu domeniu?", "Da. Conectează un domeniu de la orice registrar (GoDaddy, Namecheap, Porkbun, Cloudflare etc.) sau cumpără unul nou separat."],
      ["Pot să mă mut de pe Vercel?", "Da. Codul este un proiect Next.js standard — găzduiește-l oriunde rulează Node sau site-uri statice."],
    ],
  },
  final: {
    eyebrow: "Șase minute",
    heading: "Peste șase minute, site-ul tău poate fi online.",
    lead: "Descrie-ți afacerea, alege aspectul, plătește o dată. Îl generăm și îl publicăm în propriul tău cont.",
    secondaryCta: "Vezi prețurile",
  },
  footer: {
    blurb: "Un site complet, generat de AI și publicat în propriul tău cont. Deține-l — nu-l închiria.",
    productHeader: "Produs",
    companyHeader: "Companie",
    startHeader: "Începe acum",
    customers: "Clienți",
    waitlist: "Listă de așteptare",
    whyInsixlive: "De ce insixlive",
    createSite: "Creează-ți site-ul",
    copyright: "© 2026 insixlive. Deține-ți site-ul. Nu-l închiria.",
    builtWith: "Construit cu Next.js · Publicat pe Vercel",
  },
};
